/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as MyConcernsRouteImport } from './routes/my-concerns'
import { Route as SubmitConcernRouteImport } from './routes/submit-concern'
import { Route as TrackConcernRouteImport } from './routes/track-concern'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const MyConcernsRoute = MyConcernsRouteImport.update({
  id: '/my-concerns',
  path: '/my-concerns',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitConcernRoute = SubmitConcernRouteImport.update({
  id: '/submit-concern',
  path: '/submit-concern',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackConcernRoute = TrackConcernRouteImport.update({
  id: '/track-concern',
  path: '/track-concern',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/announcements': typeof AnnouncementsRoute
  '/contact': typeof ContactRoute
  '/my-concerns': typeof MyConcernsRoute
  '/submit-concern': typeof SubmitConcernRoute
  '/track-concern': typeof TrackConcernRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/announcements': typeof AnnouncementsRoute
  '/contact': typeof ContactRoute
  '/my-concerns': typeof MyConcernsRoute
  '/submit-concern': typeof SubmitConcernRoute
  '/track-concern': typeof TrackConcernRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/announcements': typeof AnnouncementsRoute
  '/contact': typeof ContactRoute
  '/my-concerns': typeof MyConcernsRoute
  '/submit-concern': typeof SubmitConcernRoute
  '/track-concern': typeof TrackConcernRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/announcements'
    | '/contact'
    | '/my-concerns'
    | '/submit-concern'
    | '/track-concern'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/announcements'
    | '/contact'
    | '/my-concerns'
    | '/submit-concern'
    | '/track-concern'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/announcements'
    | '/contact'
    | '/my-concerns'
    | '/submit-concern'
    | '/track-concern'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AnnouncementsRoute: typeof AnnouncementsRoute
  ContactRoute: typeof ContactRoute
  MyConcernsRoute: typeof MyConcernsRoute
  SubmitConcernRoute: typeof SubmitConcernRoute
  TrackConcernRoute: typeof TrackConcernRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-concerns': {
      id: '/my-concerns'
      path: '/my-concerns'
      fullPath: '/my-concerns'
      preLoaderRoute: typeof MyConcernsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit-concern': {
      id: '/submit-concern'
      path: '/submit-concern'
      fullPath: '/submit-concern'
      preLoaderRoute: typeof SubmitConcernRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-concern': {
      id: '/track-concern'
      path: '/track-concern'
      fullPath: '/track-concern'
      preLoaderRoute: typeof TrackConcernRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AnnouncementsRoute: AnnouncementsRoute,
  ContactRoute: ContactRoute,
  MyConcernsRoute: MyConcernsRoute,
  SubmitConcernRoute: SubmitConcernRoute,
  TrackConcernRoute: TrackConcernRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
